### PR TITLE
fix retryIf in combination with attempts 0

### PR DESCRIPTION
**Pull request by simonhoss**
Hey

This is a proposal for fixing the attempts 0 problem in combination with retryIf. Read more here #66. The idea is that the attempts 0 should not go another path.

What do you think?

### CODE REVIEW

**Comment by JaSei** [comment]
I'm not sure. I suppose some troubles with `errorLog[n]`, and `n/attempts`

**Comment by nickChenyx** [comment]
agree with @JaSei . if you want fix this "bug", i think you should do more check and add some new unit test for your code.

**Comment by merusso** [comment]
I've observed that when setting retry.Attempts(0) and cancelling a context, retry does not return an error. I wonder if this is the cause.

```go
func TestRetry_timeoutWithAttempts0(t *testing.T) {
	g := NewGomegaWithT(t)

	// Test 1, default retry.Attempts (=10)
	// Passes

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	err := retry.Do(func() error {
		return errors.New("simulated error")
	}, retry.Context(ctx))
	g.Expect(err).To(HaveOccurred())

	ctx, cancel = context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	// Test 2, retry.Attempts(0)
	// Fails

	err = retry.Do(func() error {
		return errors.New("simulated error")
	}, retry.Context(ctx), retry.Attempts(0))
	g.Expect(err).To(HaveOccurred())
}
```

**Comment by JaSei** [comment]
fixed by #86

**Pull request closed without merging**
